[mqtt]
host = "test.ota.tensor.center"
port = 1883
client_id = "vdu-LGXC14AA4B1106221"
subscribe_topic = "diagnostics/Vehicle/LGXC14AA4B1106221"
publish_topic = "diagnostics/Cloud/"
enable_tls = true
verify_peer = true
qos = 2
retain = false
ca_cert = "/userdata/fota/root.crt"
client_cert = "/userdata/fota/vehicle.crt"
client_key = "/userdata/fota/vehicle.key"

[log]
log_dir = "/tmp"
level = 0

[transport]
node_name = "domainsocket"
type = "domainsocket"
publish_topic = "/tmp/vtest_reportdata.sock"
subscribe_topic = "/tmp/vtest_cmd.sock"
buffer_size = 2000
